<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Rajesh" ignored="1" name="Order submition Test" tests="2" failures="1" timestamp="18 Sep 2022 06:09:28 GMT" time="17.588" errors="0">
  <testcase name="submitOrder" time="5.364" classname="tests.FirstTestModified"/>
  <testcase name="submitOrder" time="2.458" classname="tests.FirstTestModified">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.FirstTestModified.submitOrder(FirstTestModified.java:40)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- submitOrder -->
  <testcase name="orderHistoryTest" time="0.0" classname="tests.FirstTestModified">
    <ignored/>
  </testcase> <!-- orderHistoryTest -->
</testsuite> <!-- Order submition Test -->
